name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build source/WledSRServer.sln -c Release

      - name: Publish
        run: dotnet publish source/WledSRServer/WledSRServer.csproj -p:PublishProfile=FolderProfile -o publish

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: WledSRServer-${{ github.sha }}
          path: publish/
          retention-days: 14
